version: '3'

services:
  lavagna:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DIALECT: MYSQL
      DB_URL: jdbc:mysql://db/lavagna?useSSL=false&serverTimezone=UTC
      DB_USER: user
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 3306
      SPRING_PROFILE: dev
    volumes:
      - static-files:/tmp/static-files
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lavagna
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-files:/usr/share/nginx/html:ro
    networks:
      - frontend-network  
    restart: on-failure  
      
  
volumes:
  mysql-data:
  static-files:

networks:
  frontend-network:
  backend-network:
  
